---
name: Node continuous integration
on: push
jobs:
  build-node:
    name: Build my node
    # runs-on: windows-latest
    runs-on: ubuntu-latest
    container: node:19.3
    steps:
      - run: node --version
      - run: npm --version