---
name: Node continuous integration
on: push
jobs:
  build-node:
    name: Build my node
    # runs-on: windows-latest
    runs-on: ubuntu-latest
    container: node:19.3
    steps:
      - run: node --version
      - run: npm --version
      # run: npm install # produes error as it does not know how to pull our code in the environment
      - uses: actions/checkout@v3
      - run: dir